var TestkickCS=TestkickCS||{isRecording:!1,mousemove:!1,lastHover:[],capturedPopups:{},lastEvent:{},listeners:[{n:"click",f:"listenHandle",t:"document",e:"click"},{n:"keydown",f:"listenHandle",t:"document",e:"keydown"},{n:"input_any",f:"listenHandle",t:"input",e:"change"},{n:"input_submit",f:"listenHandle",t:"input[submit=type]",e:"submit"},{n:"input_click",f:"listenHandle",t:"input",e:"click"},{n:"textarea",f:"listenHandle",t:"textarea",e:"change"},{n:"select",f:"listenHandle",t:"select",e:"change"},
{n:"error",f:"listenHandle",t:"window",e:"error"},{n:"href",f:"listenHandle",t:"a",e:"click"},{n:"mousedown",f:"listenHandle",t:"document",e:"mousedown"},{n:"mouseup",f:"listenHandle",t:"document",e:"mouseup"},{n:"drag",f:"listenHandle",t:"document",e:"drag"},{n:"drop",f:"listenHandle",t:"document",e:"drop"}],eventFields:{MouseEvent:["clientX","clientY","offsetX","offsetY"],KeyboardEvent:["keyCode","shiftKey","ctrlKey"],ErrorEvent:["filename","colno","lineno"]},hoverHandle:function(a){lastHover.push(a.target)},
messageHandler:function(a,b){switch(a.action){case "toggleRecord":this.toggleRecord();break;case "getSelection":var c=this.getSelectedEvent();b({dataFor:"getSelection",obj:c})}},checkRecordingStatus:function(){var a=this;chrome.runtime.sendMessage({query:"isrecording"},function(b){!0===b.isrecording&&!1===a.isRecording&&a.toggleRecord()})},toggleRecord:function(){this.isRecording?this.removeListeners():(this.addListeners(),this.addLocationEvent());this.isRecording=!this.isRecording},capturedPopupEvent:function(a){var b=
a.type;a=a.result;var c={path:"builtinpopup"};c.timeStamp=Date.now();c.type=b;c.value=a;TestkickCS.sendEvent(c)},addListeners:function(){for(var a in this.listeners){var b=this.listeners[a].f,c=this.listeners[a].t,d=this.listeners[a].e;if("document"==c)$(document).on(d,this[b]);else if("window"==c)$(window).on(d,this[b]);else $(c).on(d,null,this.listeners[a],this[b])}a=document.createElement("script");a.src=chrome.extension.getURL("tkcps.js");a.id="tkcps";a.onload=function(){this.parentNode.removeChild(this)};
(document.head||document.documentElement).appendChild(a)},removeListeners:function(){for(var a in this.listeners){var b=this.listeners[a].f,c=this.listeners[a].t,d=this.listeners[a].e;"document"==c?$(document).off(d,this[b]):$(c).off(d,null,this.listeners[a],this[b])}a=new CustomEvent("removeCapturedPopups");document.dispatchEvent(a)},listenHandle:function(a){a=TestkickCS.parseEvent(a);!1!==a&&TestkickCS.sendEvent(a)},parseEvent:function(a){if(a.target==TestkickCS.lastEvent.target&&a.originalEvent.type==
TestkickCS.lastEvent.originalEvent.type)TestkickCS.lastEvent={};else{TestkickCS.lastEvent=a;var b=a.originalEvent,c={};evkey=b.toString().replace("[object ","").replace("]","");if("undefined"!==typeof TestkickCS.eventFields[evkey])for(var d in TestkickCS.eventFields[evkey]){var e=TestkickCS.eventFields[evkey][d];"undefined"!==typeof b[e]&&(c[e]=b[e].toString())}c.path=TestkickCS.getPath(a.target);c.timeStamp=b.timeStamp;c.type=b.type;c.value=b.target.value;return c}},addLocationEvent:function(){var a=
{};a.timeStamp=Date.now();a.value=window.location;a.type="open";a.path=window.location;TestkickCS.sendEvent(a)},sendEvent:function(a){TestkickCS.sendMessage({event:a})},getPath:function(a){var b={};a.id&&(b.id=a.id);a.name&&(b.name=a.name);a.href&&(b.href=a.href);a.localName&&(b.localname=a.localName.toLowerCase());a.type&&(b.type=a.type);a.className&&(b.classname=a.className);a.textContent&&(b.text=$(a).text(),"lowercase"==$(a).css("text-transform")&&(b.text=b.text.toLowerCase()),"uppercase"==$(a).css("text-transform")&&
(b.text=b.text.toUpperCase()));var c=TestkickCS.cssPath(a);a=TestkickCS.findhiddenlink(a);c&&!1!==c&&(b.path=c);!1!==a&&(b.hiddenlink=a);return b},cssPath:function(a){if(a instanceof Element){for(var b=[];a.nodeType===Node.ELEMENT_NODE;){var c=a.nodeName.toLowerCase();if("html"==c)break;if(a.id){c+="#"+a.id;b.unshift(c);break}else{for(var d=a,e=1;d=d.previousElementSibling;)d.nodeName.toLowerCase()==c&&e++;1!=e&&(c+=":nth-of-type("+e+")")}b.unshift(c);a=a.parentNode}return 0<b.length?b.join(" > "):
!1}},findhiddenlink:function(a){var b=!1;$(a).parents().not("html").each(function(){var a=$(this).css(["transition-timing-function"]),a=-1!=a["transition-timing-function"].indexOf("ease")?!0:!1,d=$(this).attr("style")&&-1!=$(this).attr("style").indexOf("visibility");(!$(this).is(":hidden")||"block"==$(this).css("display")||a||d)&&$(this).prev().each(function(){$(this)&&$(this)[0]&&$(this).attr("href")&&!b&&(b={},b.href=$(this).attr("href"),b.text=$(this).text(),b.html=$(this).html(),b.id=$(this).attr("id"));
if($(this).prev()){var a=$(this).prev();$(a)&&$(a)[0]&&$(a).attr("href")&&!b&&(b={},b.href=$(a).attr("href"),b.text=$(a).text(),b.html=$(a).html(),b.id=$(a).attr("id"))}})});return b},sendMessage:function(a){chrome.runtime.sendMessage(a,function(a){})},getSelectedEvent:function(){try{var a=document.getSelection(),b=a.getRangeAt(0).commonAncestorContainer.parentNode,c={};c.timeStamp=Date.now();c.path=this.getPath(b);c.type="selection";c.value=a.toString();return c}catch(d){}return null}};
chrome.runtime.onMessage.addListener(function(a,b,c){TestkickCS.messageHandler(a,c);return!0});document.addEventListener("popupEvent",function(a){TestkickCS.capturedPopupEvent(a.detail)});TestkickCS.checkRecordingStatus();
